from datetime import datetime, timezone

from sqlalchemy import Column, Integer, String, DateTime, Text
from .database import Base


def utcnow():
    return datetime.now(timezone.utc)


class User(Base):
    """Login credentials for the WebUI itself."""
    __tablename__ = "users"

    id            = Column(Integer, primary_key=True, index=True)
    username      = Column(String(100), unique=True, nullable=False, index=True)
    password_hash = Column(String(255), nullable=False)
    created_at    = Column(DateTime(timezone=True), default=utcnow)


class Account(Base):
    """A Roblox account generated by DeltaCore."""
    __tablename__ = "accounts"

    id           = Column(Integer, primary_key=True, index=True)
    username     = Column(String(150), nullable=False, index=True)
    password     = Column(String(1000), nullable=False)
    account_type = Column(String(100), nullable=False, default="+30 days old")
    cookie       = Column(Text, nullable=True, default="")
    region       = Column(String(10), nullable=True, default="")
    created_at   = Column(DateTime(timezone=True), default=utcnow)
    updated_at   = Column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
